---
# Grant OpenShift GitOps permissions to manage cluster-wide resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-gitops-cluster-manager
rules:
  # Permissions for OpenStack resources
  - apiGroups:
      - "core.openstack.org"
      - "network.openstack.org"
      - "dataplane.openstack.org"
      - "telemetry.openstack.org"
      - "heat.openstack.org"
      - "ironic.openstack.org"
      - "manila.openstack.org"
      - "ovn.openstack.org"
      - "rabbitmq.openstack.org"
      - "neutron.openstack.org"
      - "nova.openstack.org"
      - "cinder.openstack.org"
      - "glance.openstack.org"
      - "keystone.openstack.org"
      - "placement.openstack.org"
      - "mariadb.openstack.org"
      - "octavia.openstack.org"
      - "barbican.openstack.org"
      - "horizon.openstack.org"
    resources:
      - "*"
    verbs:
      - "*"
  # Permissions for Kubernetes core resources
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
      - services
      - serviceaccounts
      - persistentvolumes
      - persistentvolumeclaims
      - pods
      - pods/log
    verbs:
      - "*"
  # Permissions for Namespace management (labels/annotations)
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  # Permissions for storage
  - apiGroups:
      - "storage.k8s.io"
    resources:
      - storageclasses
      - volumeattachments
    verbs:
      - "*"
  # Permissions for batch jobs
  - apiGroups:
      - "batch"
    resources:
      - jobs
      - cronjobs
    verbs:
      - "*"
  # Permissions for RBAC
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs:
      - "*"
  # Permissions for Apps
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - statefulsets
      - daemonsets
    verbs:
      - "*"
  # Permissions for Routes
  - apiGroups:
      - "route.openshift.io"
    resources:
      - routes
    verbs:
      - "*"
  # Permissions for NNCP (NodeNetworkConfigurationPolicy)
  - apiGroups:
      - "nmstate.io"
    resources:
      - nodenetworkconfigurationpolicies
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  # Permissions for MetalLB
  - apiGroups:
      - "metallb.io"
    resources:
      - ipaddresspools
      - l2advertisements
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  # Permissions for Network Attachment Definitions (NAD)
  - apiGroups:
      - "k8s.cni.cncf.io"
    resources:
      - network-attachment-definitions
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-gitops-cluster-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-gitops-cluster-manager
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
