---
# IMPORTANT: SSH keys have been removed for security
#
# To use this configuration:
# 1. Generate your SSH keypair: ssh-keygen -t rsa -b 4096 -f ~/.ssh/dataplane_key
# 2. Replace the placeholder values below with your actual keys:
#    - ssh-privatekey: Contents of ~/.ssh/dataplane_key
#    - ssh-publickey: Contents of ~/.ssh/dataplane_key.pub
# 3. Make sure to deploy the public key to your EDPM compute nodes
#
# See README.md for detailed setup instructions
apiVersion: v1
kind: Secret
metadata:
  name: dataplane-ansible-ssh-private-key-secret
  annotations:
    argocd.argoproj.io/sync-wave: "9"
type: Opaque
stringData:
  ssh-privatekey: |
    # REPLACE WITH YOUR SSH PRIVATE KEY
    # Format: -----BEGIN OPENSSH PRIVATE KEY-----
    #         <base64 encoded key data>
    #         -----END OPENSSH PRIVATE KEY-----
  ssh-publickey: |
    # REPLACE WITH YOUR SSH PUBLIC KEY
    # Format: ssh-rsa AAAA... user@host
