#!/bin/bash
#
# Generate kustomization patches for MetalLB pool annotations in OpenStackControlPlane CR
# This script is called by the wrapper's controlplane target to inject namespace-prefixed
# MetalLB pool names into the OpenStackControlPlane CR BEFORE deployment.
#
# Usage:
#   NAMESPACE=openstack2 DEPLOY_DIR=/path/to/deploy bash gen-metallb-pool-kustomization.sh

set -e

if [ -z "$NAMESPACE" ]; then
    echo "Error: NAMESPACE not set" >&2
    exit 1
fi

if [ -z "$DEPLOY_DIR" ]; then
    echo "Error: DEPLOY_DIR not set" >&2
    exit 1
fi

# Construct namespace-prefixed pool names
# These match the pools created by upstream's gen-metallb-config.sh when OPENSTACK_NAMESPACE is set
CTLPLANE_POOL="${NAMESPACE}-ctlplane"
INTERNALAPI_POOL="${NAMESPACE}-internalapi"
STORAGE_POOL="${NAMESPACE}-storage"
TENANT_POOL="${NAMESPACE}-tenant"

echo "Generating MetalLB pool kustomization patches for namespace: ${NAMESPACE}"
echo "  CtlPlane pool: ${CTLPLANE_POOL}"
echo "  InternalAPI pool: ${INTERNALAPI_POOL}"
echo "  Storage pool: ${STORAGE_POOL}"
echo "  Tenant pool: ${TENANT_POOL}"

# Append patches to existing kustomization.yaml
# These patches add the metallb.universe.tf/address-pool annotations to each service
cat <<EOF >>"${DEPLOY_DIR}/kustomization.yaml"
# MetalLB pool annotations for multi-RHOSO namespace: ${NAMESPACE}
# Generated by wrapper's gen-metallb-pool-kustomization.sh
- target:
    kind: OpenStackControlPlane
  patch: |-
    - op: add
      path: /spec/dns/template/override/service/metadata/annotations/metallb.universe.tf~1address-pool
      value: ${CTLPLANE_POOL}
    - op: add
      path: /spec/glance/template/glanceAPIs/default/override/service/internal/metadata/annotations/metallb.universe.tf~1address-pool
      value: ${INTERNALAPI_POOL}
    - op: add
      path: /spec/cinder/template/cinderAPI/override/service/internal/metadata/annotations/metallb.universe.tf~1address-pool
      value: ${INTERNALAPI_POOL}
    - op: add
      path: /spec/barbican/template/barbicanAPI/override/service/internal/metadata/annotations/metallb.universe.tf~1address-pool
      value: ${INTERNALAPI_POOL}
    - op: add
      path: /spec/designate/template/designateAPI/override/service/internal/metadata/annotations/metallb.universe.tf~1address-pool
      value: ${INTERNALAPI_POOL}
    - op: add
      path: /spec/heat/template/heatAPI/override/service/internal/metadata/annotations/metallb.universe.tf~1address-pool
      value: ${INTERNALAPI_POOL}
    - op: add
      path: /spec/heat/template/heatEngine/override/service/internal/metadata/annotations/metallb.universe.tf~1address-pool
      value: ${INTERNALAPI_POOL}
    - op: add
      path: /spec/swift/template/swiftProxy/override/service/internal/metadata/annotations/metallb.universe.tf~1address-pool
      value: ${INTERNALAPI_POOL}
    - op: add
      path: /spec/keystone/template/override/service/internal/metadata/annotations/metallb.universe.tf~1address-pool
      value: ${INTERNALAPI_POOL}
    - op: add
      path: /spec/manila/template/manilaAPI/override/service/internal/metadata/annotations/metallb.universe.tf~1address-pool
      value: ${INTERNALAPI_POOL}
    - op: add
      path: /spec/nova/template/apiServiceTemplate/override/service/internal/metadata/annotations/metallb.universe.tf~1address-pool
      value: ${INTERNALAPI_POOL}
    - op: add
      path: /spec/nova/template/metadataServiceTemplate/override/service/metadata/annotations/metallb.universe.tf~1address-pool
      value: ${TENANT_POOL}
    - op: add
      path: /spec/neutron/template/override/service/internal/metadata/annotations/metallb.universe.tf~1address-pool
      value: ${INTERNALAPI_POOL}
    - op: add
      path: /spec/placement/template/override/service/internal/metadata/annotations/metallb.universe.tf~1address-pool
      value: ${INTERNALAPI_POOL}
    - op: add
      path: /spec/rabbitmq/templates/rabbitmq/override/service/metadata/annotations/metallb.universe.tf~1address-pool
      value: ${INTERNALAPI_POOL}
    - op: add
      path: /spec/rabbitmq/templates/rabbitmq-cell1/override/service/metadata/annotations/metallb.universe.tf~1address-pool
      value: ${INTERNALAPI_POOL}
    - op: add
      path: /spec/ovn/template/ovnDBCluster/ovndbcluster-nb/override/service/metadata/annotations/metallb.universe.tf~1address-pool
      value: ${INTERNALAPI_POOL}
    - op: add
      path: /spec/ovn/template/ovnDBCluster/ovndbcluster-sb/override/service/metadata/annotations/metallb.universe.tf~1address-pool
      value: ${INTERNALAPI_POOL}
    - op: add
      path: /spec/ovn/template/ovnNorthd/override/service/metadata/annotations/metallb.universe.tf~1address-pool
      value: ${INTERNALAPI_POOL}
EOF

echo "✅ MetalLB pool patches appended to ${DEPLOY_DIR}/kustomization.yaml"
